import { FastifyInstance } from "fastify";
import { mediaController } from "./media.controller";
import { requirePermission } from "@/plugins/rbac";
import {
  idParam,
  jsonBody,
  ok,
  okMessage,
  okPaged,
  op,
  pageQuery,
  plainError,
  queryParams,
  str,
} from "@/schemas/common";
import { mediaItemSchema, mediaSchema } from "@/schemas/entities";

const TAGS = ["Media"];
const ACCESS = "SUPER_ADMIN, ADMIN, or an EDITOR granted the `media` module";

export async function registerMediaRoutes(fastify: FastifyInstance) {
  fastify.post(
    "/admin/media/upload",
    {
      preHandler: requirePermission("media"),
      schema: op({
        tags: TAGS,
        summary: "Upload a file to the media library",
        description: [
          "`multipart/form-data` with a single file part named **`file`**. Put the target folder in the `folder` **query string**, not the form body.",
          "",
          "The MIME type is sniffed from the bytes, not trusted from the client. Images are limited to 10 MB and are converted to WebP with `thumb`, `medium`, `large`, and `og` renditions generated by sharp; the URLs land in `variants`.",
          "",
          "```bash",
          'curl -X POST "$API/api/v1/admin/media/upload?folder=/gallery" \\',
          '  -H "Authorization: Bearer $TOKEN" \\',
          '  -F "file=@kunda.jpg"',
          "```",
        ].join("\n"),
        access: ACCESS,
        consumes: ["multipart/form-data"],
        query: queryParams({
          folder: str("Virtual folder to file the upload under.", {
            default: "/",
            example: "/gallery",
          }),
        }),
        response: {
          201: ok("The stored file.", mediaItemSchema),
          400: plainError("The request carried no file part.", "No file uploaded"),
        },
      }),
    },
    (request, reply) => mediaController.uploadMedia(request, reply)
  );

  fastify.get(
    "/admin/media",
    {
      preHandler: requirePermission("media"),
      schema: op({
        tags: TAGS,
        summary: "Browse the media library",
        description: "Files newest first, optionally narrowed to one folder. This is what the media picker reads.",
        access: ACCESS,
        query: queryParams({
          folder: str("Return only files in this folder. Omit for all folders.", {
            example: "/gallery",
          }),
          ...pageQuery(20),
        }),
        response: {
          200: okPaged("A page of media.", "media", mediaItemSchema, "Files on this page."),
        },
      }),
    },
    (request, reply) => mediaController.listMedia(request, reply)
  );

  fastify.get(
    "/admin/media/:id",
    {
      preHandler: requirePermission("media"),
      schema: op({
        tags: TAGS,
        summary: "Get one media file",
        description: "Full metadata including the generated `variants` map, which the list endpoint omits.",
        access: ACCESS,
        params: idParam("media"),
        response: {
          200: ok("The file.", mediaSchema),
        },
      }),
    },
    (request, reply) => mediaController.getMedia(request, reply)
  );

  fastify.patch(
    "/admin/media/:id",
    {
      preHandler: requirePermission("media"),
      schema: op({
        tags: TAGS,
        summary: "Edit media metadata",
        description:
          "Changes alt text and/or folder. The stored bytes are never touched, so URLs stay valid. Send only the fields you want to change.",
        access: ACCESS,
        params: idParam("media"),
        body: jsonBody("Fields to change. Both are optional.", {
          alt: str("Alt text used wherever the image is rendered.", {
            example: "Steps leading down to Radha Kunda at dawn",
          }),
          folder: str("Move the file into this folder.", { example: "/gallery" }),
        }),
        response: {
          200: ok(
            "The updated file. Only the identity and edited fields are echoed back.",
            mediaItemSchema
          ),
        },
      }),
    },
    (request, reply) => mediaController.updateMedia(request, reply)
  );

  fastify.delete(
    "/admin/media/:id",
    {
      preHandler: requirePermission("media"),
      schema: op({
        tags: TAGS,
        summary: "Delete a media file",
        description: [
          "Removes the row and the blobs in Azure Blob Storage, including every generated variant.",
          "",
          "References from posts, authors, and gallery covers are set to null. A file still used as a gallery image cannot be deleted — that returns 409.",
        ].join("\n"),
        access: ACCESS,
        params: idParam("media"),
        errors: [409],
        response: {
          200: okMessage("The file was deleted.", "Media deleted"),
        },
      }),
    },
    (request, reply) => mediaController.deleteMedia(request, reply)
  );
}
